licenses(["notice"])
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test",
    copts = [
        "-I./src",
    ],
    hdrs = [
        "catch.hpp",
    ],
    srcs = [
        "catch.test.cpp",
    ],
)
